[package]
name = "sudoku"
version = "0.1.0"
authors = ["dominickt"]
edition = "2018"

[dependencies]
rayon = "1.10.0"
clap = { version = "4.5.27", features = ["derive"] }

[profile.release]
debug = true
opt-level = 3

[profile.release.package."*"]
debug = true
opt-level = 3
