[package]
name = "sudoku"
version = "0.1.0"
authors = ["dominickt"]
edition = "2018"

[dependencies]
structopt = "0.3"
rayon = "*"

[profile.release]
debug = true
opt-level = 3

[profile.release.package."*"]
debug = true
opt-level = 3
